# Generated by Django 4.0.6 on 2022-08-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_lead_date_added_lead_description_lead_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackGround',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img')),
            ],
        ),
    ]
